- .gitignore
- go.mod
- main.go
Layout the main.go file, initialize go mod, and ignore the build binary.
Future patches will expand on this to start including a protocol buffer
definition for the API.
> Add basic golang skeleton

- Makefile
- README.md
Let's add a build target for creating builds so it's easy to invoke and
consistent as the project grows.
Fixes #9
> Add a make file and target for building binaries

- main.go
We don't need this since we're putting the main entrypoint for the
service in the cmd/ directory. Let's remove this since it's not
necessary and just produces and empty binary when you build from the
root of the repository.
> Remove the main.go file

- Makefile
We need this as the entrypoint for running tests using the OpenShift CI.
> Add a makefile target for tests

- .github/workflows/migrations.yml
- .gitignore
- Makefile
- migrations/README.md
- migrations/test.sh
- make: Add a target to download the migrate binary
Adds a `make migrate` target for the Makefile that fetches
the migrate CLI. Adds several top-level Makefile variables for
autodetection of the OS and the arch so that we support different OS-es
and arches from the start.
- tests: Add a GH action test for the DB migrations
Adds a github action that spawns a postgres container and runs migrate
up and migrate down to exercise our database migrations.
> Add test for db migrations

- README.md
- kustomize/deployment.yaml
- kustomize/kustomization.yaml
- kustomize/secret.yaml
- kustomize/service.yaml
This commit adds basic plumbing to use kustomize to deploy a postgres
database on a kubernetes deployment. This will expand to include the
actual compliance service application. For now, it's focused solely on
the database so it can be used for development purposes.
Related to #22
> Add basic kustomize support

- Makefile
- migrations/test.sh
- Also make the download of migrate conditional; If `MIGRATE=` is set in the
environment for `make` it will use that, otherwise it will look in PATH. If
neither are available it will download migrate locally into tools/.
> Add test-migrate Makefile target

- .github/workflows/go.yml
- .golangci.yml
- Makefile
- cmd/compserv-server.go
- pkg/api/server.go
- pkg/config/config.go
- make: Add a Makefile target that runs golangci-lint
Adds a new make target 'make verify' that is meant to run all the linters and code checks we'll have. For now, there's a single dependency `make verify-go-lint` that runs the golangci-lint linter.
- Fix linter errors reported by golangci-lint
Please see its commit message for all the fixes
- Add a github action to run the linter on every commit
what the title says
> Add golangci-lint

- Makefile
- README.md
Add the ability to deploy the compliance service using kustomize and an
existing Kubernetes cluster.
Additionally patches will add more functionality to kustomize to support
deploying the actual compliance service. This patch will be referenced
in the openshift/release configuration to ensure kustomize is used to
deploy the application in CI.
Fixes #43
> Add a makefile target for `deploy`

- kustomize/kustomization.yaml
- kustomize/namespace.yaml
While running `kubectl apply -k kustomize` will put the resources in the
default namespace, this apparently isn't possible in CI. The e2e-aws CI
fails with an error similar to the following:
./tools/kubectl apply -k kustomize
Error from server (NotFound): error when creating "kustomize": namespaces "ci-op-lct9f0l5" not found
Instead of relying on a namespace, we can be explicit by specifying the
namespace we want to deploy resources to.
This commit updates the kustomize files to create a namespace and use
that namespace for resources.
> Add a namespace for the service to kustomize

- Makefile
- migrations/test.sh
- utils/functions.sh
The test.sh script we use to test database migrations contains useful
commands that we can re-use in other tests.
This commit pulls those useful bits into a common file under utils/ and
sources them from test.sh. Future patches will use these functions for
testing the database layer directly against a PostgreSQL container.
> Refactor useful functions from test.sh

- utils/run_integration_tests.sh
The current integration tests are specific to testing PostgreSQL, and
it's state can affect tests depending on what they assert. To prevent
transient issues where multiple tests are changing the state of the same
database, we should run them serially.
> Ensure integration tests run serially

- .gitignore
Initially, we were using a migrate binary in the root of the project
repository. Since then we've moved it to a tools/ directory with similar
utilities and we just ignore that.
By ignoring migrate, we potentially match any dependency names in vendor
(like golang-migrate/migrate).
Let's remove this so we can actually use migrate.
Fixes #72
> Don't ignore migrate

- .github/dependabot.yml
Let's use dependabot:
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
https://help.github.com/en/github/administering-a-repository/about-github-dependabot
to keep our dependencies up-to-date and avoid CVEs in our code.
Dependabot would try to add the `/ok-to-test` label so that our CI runs
automatically.
> Use dependabot to keep our deps up2date

- tests/helpers.go
- tests/integration_test.go
Before, we nested the integration tests in tests/integration and the
package name was integration_test. This caused some linting issues where
the linter expected the package name to be integration (presumably
because of the directory name).
This commit address two different linting issues by removing a noop
linting check and disabling testpackage linting on the integration test
package line. Without disabling linting in this case, the linter expects
to have the package name be `integration_test_test`. Renaming the file
to `integration` won't run any tests since golang expects to run tests
against files ending in _test.go.
This commit also takes the opportunity to remove a layer in the tests
directory. For now, we can keep the structure simple and add more layers
when we actually need …
> Restructure test packaging

- go.mod
- tests/constants.go
- tests/helpers.go
- tests/integration_test.go
- tests/utils.go
This commit introduces some better organization to the integration tests
by renaming helpers.go to utils.go, moving utility methods out of the
test module (integration_test.go), and creates a new place for
constants.
This commit also removed a direct dependency on github.com/lib/pq in the
integration tests (the tests still execute successfully without this
dependency, so we can clean it up).
> Organize integration tests

- tests/utils.go
Previously, we were using fmt.Sprintf to create strings with error
messages and then passing that to t.Skip(msg). The testing module
supports t.Skipf(), which handles formatting. Let's use that instead.
This commit also adds relevant error messages to logs by incorporating
them with pre-existing error messages using Skipf().
> Cleanup usage of Skip in integration tests

- README.md
As we work through schema design and migrations, it would be nice to
know how we handle certain common things, like IDs and datetime.
Let's include those in the README.md next to the design goals. This was
mentioned while working through schemas in #84.
> Document how the service handles IDs and datetimes

- migrations/000003_add_subject_parent_id.down.sql
- migrations/000003_add_subject_parent_id.up.sql
- tests/integration_test.go
- tests/utils.go
We want to be able to nest subjects and build a hierarchical
relationship between them. This commit does that by adding a database
migration that adds a new column for parent_id and adds a FK
relationship to it.
This approach was discussed in https://github.com/rhmdnd/compserv/issues/84
> Implement a foreign key for subjects

- kustomize/deployment.yaml
The postgres container would fail trying to chmod the data directory,
which was the same as the volumemount. Set PGDATA to a `data`
subdirectory to fix this.
> Set PGDATA for Kube deployment

- migrations/000004_add_assessments_table.down.sql
- migrations/000004_add_assessments_table.up.sql
- tests/integration_test.go
- tests/utils.go
The commit adds a new database table for assessments, which are
groupings of results (e.g., scans). This helps organize results based on
assessments of systems or clusters.
This schema was discussed in https://github.com/rhmdnd/compserv/issues/84
Fixes #118
> Add a table for assessments

- tests/integration_test.go
This fmt.Println() was left over from introducing metadata testing.
> trivial: Cleanup litter in integration_test.go

- tests/integration_test.go
- tests/utils.go
Each functional test should drop the database when it's done. This
ensures a clean database for the next test and prevents tests from
assuming a specific run order.
> trivial: Add missing database cleanup to functional tests

- tests/integration_test.go
Before, we had some instances where the migration version mismatched
the version in the test error message. Let's fix that so it's not
confusing.
> Ensure migration version matches error messages

- tests/integration_test.go
The assessment table migration landed before we merge a generic cleanup
utility for database.
https://github.com/rhmdnd/compserv/pull/121
The m.Drop() calls in the assessment tests are redundant and
unnecessary. Let's clean them up.
> trivial: Remove unnecessary cleanup calls in assessment tests

- migrations/000005_add_subject_metadata_id.down.sql
- migrations/000005_add_subject_metadata_id.up.sql
- tests/integration_test.go
- tests/utils.go
The database has a table for metadata, which can be useful for subjects.
Let's add a foreign key to the subject table so we can use metadata with
it.
Fixes #119
> Add metadata_id column to subject table

- migrations/000006_create_catalogs_table.down.sql
- migrations/000006_create_catalogs_table.up.sql
- tests/integration_test.go
Create a table that contains catalogs (ideally written in OSCAL), that
can be parsed to provide information on controls as it was written by
the benchmark authors.
This is being discussed in issue #84.
> Add a table for catalogs

- migrations/000007_create_profiles_table.down.sql
- migrations/000007_create_profiles_table.up.sql
- tests/integration_test.go
This commit adds a table for profiles so that we can reference controls,
and results to a parent profile.
This table is not designed, at least initially, to store more than just
a profile name and some metadata. This area will be tricky to navigate
moving forward since it would be idea to rely on OSCAL defintions for
profiles, and use OSCAL profiles distributed by standards bodies, and
not maintain them in a service.
This approach is being discussed in issue #84.
> Add a table for profiles

- migrations/000008_create_controls_table.down.sql
- migrations/000008_create_controls_table.up.sql
- tests/integration_test.go
This table adds a basic schema for controls, which will be referenced by
results.
Ideally, this control information will supplement information from other
sources like OSCAL catalogs, which should be the preferred source of
information, since it comes from the profile/standard authors.
This schema is being discussed in issue #84.
> Add a table for controls

- Makefile
- README.md
- migrations/schema.sql
- utils/update_schema_doc.sh
Add a make target for generating the schema from the migrations and
including it in the database documentation.
This is useful for having a holistic view of the database, instead of
sifting through migrations to understand the relationships between all
tables. The included .sql file is only for documentation purposes.
Fixes #84
> Document the database schema

- cmd/compserv-server.go
- pkg/config/config.go
We use viper to parse configuration. Previously, we would use the library to set defaults, parse configuration, and lookup values. Then, we'd put that into a map for other parts of the compliance service to use.
This just introduced a middle layer in configuration handling that wasn't necessary. Instead, let's just pass back an instance of the viper configuration handler and let parts of the application call the values they need out of it using `viper.GetString()`.
This is less error prone since it doesn't require maintainers to keep a extra mental mapping between viper configuration and an internal map.
> Simplify configuration handling

- cmd/compserv-server.go
Previously, we'd log information about the database instance when connecting to it (e.g., memory address), but this information didn't really include anything useful from an operations standpoint.
Let's log the actual database endpoint instead, so it's more clear what the service is actually connecting to.
> Improve database connection logging

- pkg/config/config.go
- pkg/config/secrets.go
This commit adds better logging for invalid configuration. It also moves
the AWS getSecret method into a separate file specifically for handling
secrets (secrets.go). When we add support for kubernetes secrets, we'll
update this file to contain a similar implementation for fetching
kubernetes secrets.
> Improve configuration validation and secret handling

- .gitignore
Git ignore is greedy, meaning `tools/` will match any subdirectory in
the repository, not just the `tools/` we use at the root. This is a
problem if we have a lot of dependencies that might have a directory in
their package called `tools/`, or anything else we ignore.
Let's be explicit in ignoring our own tools and builds so that we don't
accidentally ignore something a dependency needs.
> Explicitly ignore builds and tools

- configs/sample-config.yaml
We're updating the password configuration code to support other secret managers. This commit updates the sample configuration to reflect reality when https://github.com/rhmdnd/compserv/pull/167 lands.
> Update sample configuration for passwords

- Makefile
We download development dependencies in tools/ and put builds in
builds/. Let's add a makefile target to clean up these directories since
we also have automation for build and downloading fresh copies.
> Add a Makefile target for cleaning tools and builds

- Makefile
Use ?= instead of := for default values. This makes it so they can be
overridden.
> Fix default values in Makefile
